TRUNCATE TABLE incidentes RESTART IDENTITY CASCADE;
TRUNCATE TABLE partidos RESTART IDENTITY CASCADE;
TRUNCATE TABLE jugadores RESTART IDENTITY CASCADE;
TRUNCATE TABLE equipos RESTART IDENTITY CASCADE;
TRUNCATE TABLE competiciones RESTART IDENTITY CASCADE;
